name: Daily Update
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install
        run: pip install -r requirements.txt
      - name: Build
        run: python generator.py
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Daily Update
          file_pattern: '*.html'
