name: Do things every 5 minutes
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: pip install -r requirements.txt
      - name: Build
        run: python generator.py
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.html'
          commit_message: 'Daily Update'
